export default {
	// 员工合同申请导入
	CONTRACT_APPLY_HEADER: {
		empName: '员工姓名',
		empIdcard: '身份证号',
		deptNo: '项目编码',
		situation: '签订类型',
		contractName: '合同类型',
		contractSubName: '业务细分',
		reason: '原因说明',
		contractParty: '合同甲方',
		contractType: '签订期限',
		contractStart: '起始日期',
		contractEnd: '截止日期',
		post: '合同岗位',
		workingHours: '工时制',
		contractNo: '合同编码',
		fileCabinetNo: '档案柜号',
		leaveDate:'离职日期',
		reduceReason:'终止原因',
		remark: '备注',
		
	},

	// 员工合同归档批量更新
	CONTRACT_FILE_HEADER: {
		applyNo: '合同申请编码',
		empName: '员工姓名',
		contractNo: '合同编码',
		fileCabinetNo: '档案柜号',
	},

	/**
	 * 电子合同批量导入头部
	 */
	ELE_CONTRACT_IMPORT_HEADER: {
		empName: '员工姓名',
		empIdcard: '身份证号',
		deptNo: '项目编码',
		empNatrue:'员工类型',
		empPhone: '手机号码',
		contractStart: '合同起始时间',
		contractEnd: '合同到期时间',
		periodStart: '合同试用期开始时间',
		periodEnd: '合同试用期结束时间',
		periodSalaryPerMonth: '试用期工资',
		salaryType: '工资形式',
		salaryStandardPerHour: '计时工资',
		salaryStandardPerPiece: '计件工资',
		workSpace: '工作地点',
		post: '岗位',
	},

	// 员工合同导出
	CONTRACT_EXPORT_HEADER: [
		{ title: '审核类型', dataIndex: 'type', width: 100 },
		{ title: '申请编号', dataIndex: 'applyNo', width: 100 },
		{ title: '员工编号', dataIndex: 'empNo', width: 100 },
		{ title: '员工姓名', dataIndex: 'empName', width: 100 },
		{ title: '身份证号', dataIndex: 'empIdcard', width: 100 },
		{ title: '合同起始日期', dataIndex: 'contractStart', width: 100 },
		{ title: '合同截止日期', dataIndex: 'contractEnd', width: 100 },
		{ title: '档案所在省', dataIndex: 'fileProvince', width: 100 },
		{ title: '档案所在市', dataIndex: 'fileCity', width: 100 },
		{ title: '档案所在县', dataIndex: 'fileTown', width: 100 },
		{ title: '项目名称', dataIndex: 'subjectDepart', width: 100 },
		{ title: '项目编码', dataIndex: 'deptNo', width: 100 },
		{ title: '员工类型', dataIndex: 'empNatrue', width: 100 },
		{ title: '合同类型', dataIndex: 'contractName', width: 100 },
		{ title: '业务细分', dataIndex: 'contractSubName', width: 100 },
		{ title: '签订类型', dataIndex: 'situation', width: 100 },
		{ title: '签订期限', dataIndex: 'contractType', width: 100 },
		{ title: '合同甲方', dataIndex: 'contractParty', width: 100 },
		{ title: '客户名称', dataIndex: 'subjectUnit', width: 100 },
		{ title: '审核状态', dataIndex: 'auditStatus', width: 100 },
		{ title: '合同状态', dataIndex: 'inUse', width: 100 },
		{ title: '附件状态', dataIndex: 'files', width: 100 },
		{ title: '归档状态', dataIndex: 'isFile', width: 100 },
		{ title: '创建人', dataIndex: 'createName', width: 100 },
		{ title: '创建时间', dataIndex: 'createTime', width: 100 },
	],

	// 员工合同导出【合并历史】
	CONTRACT_EXPORT_HEADER_HISTORY: [
		{ title: '申请编号', dataIndex: 'applyNo', width: 100 },
		{ title: '员工编号', dataIndex: 'empNo', width: 100 },
		{ title: '员工姓名', dataIndex: 'empName', width: 100 },
		{ title: '身份证号', dataIndex: 'empIdcard', width: 100 },
		{ title: '合同起始日期', dataIndex: 'contractStart', width: 100 },
		{ title: '合同截止日期', dataIndex: 'contractEnd', width: 100 },
		{ title: '档案所在省', dataIndex: 'fileProvince', width: 100 },
		{ title: '档案所在市', dataIndex: 'fileCity', width: 100 },
		{ title: '档案所在县', dataIndex: 'fileTown', width: 100 },
		{ title: '项目名称', dataIndex: 'subjectDepart', width: 100 },
		{ title: '项目编码', dataIndex: 'deptNo', width: 100 },
		{ title: '员工类型', dataIndex: 'empNatrue', width: 100 },
		{ title: '合同类型', dataIndex: 'contractName', width: 100 },
		{ title: '业务细分', dataIndex: 'contractSubName', width: 100 },
		{ title: '签订类型', dataIndex: 'situation', width: 100 },
		{ title: '签订期限', dataIndex: 'contractType', width: 100 },
		{ title: '合同甲方', dataIndex: 'contractParty', width: 100 },
		{ title: '客户名称', dataIndex: 'subjectUnit', width: 100 },
		{ title: '审核状态', dataIndex: 'auditStatus', width: 100 },
		{ title: '合同状态', dataIndex: 'inUse', width: 100 },
		{ title: '附件状态', dataIndex: 'files', width: 100 },
		{ title: '归档状态', dataIndex: 'isFile', width: 100 },
		{ title: '创建人', dataIndex: 'createName', width: 100 },
		{ title: '创建时间', dataIndex: 'createTime', width: 100 },
		{ title: '累计签订次数', dataIndex: 'createNum', width: 100 },
		// {title:'历次记录',dataIndex: 'history', width: 160},
		{ title: '首签日期', dataIndex: 'startDate', width: 100 },
		{ title: '最晚到期日期', dataIndex: 'endDate', width: 100 },
	],

	// 续签待办导出
	CONTRACT_EXPORT_HEADER_RENEW: [
		{header: '员工编号', key: 'empCode', width: 15},
		{header: '员工姓名', key: 'empName', width: 15},
		{header: '身份证号', key: 'empIdcard', width: 20},
		{header: '合同起始日期', key: 'contractStart', width: 15},
		{header: '合同截止日期', key: 'contractEnd', width: 15},
		{header: '档案所在省', key: 'fileProvince', width: 15},
		{header: '档案所在市', key: 'fileCity', width: 15},
		{header: '档案所在县', key: 'fileTown', width: 15},
		{header: '项目名称', key: 'project', width: 25},
		{header: '项目编码', key: 'projectNo', width: 20},
		{header: '员工类型', key: 'empType', width: 15},
		{header: '合同类型', key: 'contractType', width: 15},
		{header: '签订期限', key: 'contractTerm', width: 15},
		{header: '距离到期天数', key: 'daysDue', width: 15},
		{header: '是否过期', key: 'dueFlag', width: 15},
		{header: '过期天数', key: 'daysOver', width: 15},
		{header: '首次提醒时间', key: 'firstAlertTime', width: 15},
		{header: '提醒人', key: 'alertPerson', width: 15},
	],

	/**
	 * 合同审核字典对应
	 */
	CONTRACT_AUDIT_PARAMS: {

		empName: '员工姓名',
		subjectDepart: '项目名称',
		empNatrue: '员工类型',
		situation: '签订类型',
		leaveDate: '离职日期',
		reduceReason:'终止原因',
		
		contractName: '合同类型',
		
		subjectUnit: '客户名称',
		contractParty: '合同甲方',
		contractType: '签订期限',
		contractStart: '起始日期',
		contractEnd: '截止日期',
		reason: '原因说明',

		contractSubName: '业务细分',
		type: '审核类型',
		contractTerm: '合同年限',
		post: '合同岗位',
		workingHours: '工时制',
		contractNo: '合同编码',
		fileCabinetNo: '档案柜号',
		remark: '备注',
		file: '附件上传',
	},
};
